### ISSUE TITLE
실행 환경 관련 문의 사항

### ISSUE THREAD

**Issue by Abel3005** [DatathonInfo/MISOChallenge-3Dobject#2]
## 실행환경 관련 문의사항
<br> Docker를 사용하여 주어진 환경에서 무리없이 잘 동작하는 프로그램을 제작해도 될까요?

**Comment by qnqnckck** [comment]
Docker로 사용해도 상관없습니다. 검증시에 바로 테스트 가능하도록 정확한 실행 가이드 문서를 같이 작성 해주시기 바랍니다.

**Comment by Abel3005** [comment]
넵 답변 감사합니다.
