### ISSUE TITLE
학습 데이터 관련 문의

### ISSUE THREAD

**Issue by Abel3005** [DatathonInfo/MISOChallenge-3Dobject#3]
## 학습데이터 관련 문의
주어진 데이터가 RGB +D 데이터라고 하여 뎁스이미지를 계속 찾고 있는데 Depth이미지가 안 주어져있는 것 같습니다. 
<br>입력 데이터로 주어질 뎁스 정보를 어느 곳에서 찾을 수 있을까요?

**Comment by qnqnckck** [comment]
제공되는 타입은 RGB 데이터이며, RGB+D는 LINMOD의 홈페이지 정의를 그대로 설명한 부분이오니 혼선 없으시기 바랍니다.
