### ISSUE TITLE
서버 접속 방법 문의

### ISSUE THREAD

**Issue by SIDED00R** [DatathonInfo/MISOChallenge-3Dobject#6]
![image](https://user-images.githubusercontent.com/90430452/142714110-9f573715-3970-4581-85a4-485292db1eee.png)
혹시 이와 같이  jupyter notebook --port 8888을 입력할 경우 요청한 주소에 배정할 수 없다고 뜨는데 어떻게 접속해야 하는지 알 수 있을까요?

**Comment by qnqnckck** [comment]
안녕하세요 참가자님
주피터 기본 설치로 제공되고있습니다. 해당명령어 실행없이 http://ip:port로 브라우저로 접속해보시기 바랍니다
감사합니다
