### ISSUE TITLE
결과제출 문의

### ISSUE THREAD

**Issue by steve-yskim** [DatathonInfo/MISOChallenge-3Dobject#7]
안녕하세요 결과제출 문의드립니다
모델의 weight를 3d-object별로 도출한 후 이메일로 제출하나요?
아니면 최종 모델이 ' [프로젝트 홈]/backup/[데이터셋명]/model.weights' 에 저장되어있으면 되나요?

감사합니다

**Comment by steve-yskim** [comment]
그리고 모델 weight가 결국 20개 나와야하는 것이 맞지요?

**Comment by qnqnckck** [comment]
안녕하세요 참가자님
이메일 제출도 같이 부탁드리며  20개의 weight가 나와야하는게 맞습니다. 
감사합니다.
