### ISSUE TITLE
결과 요약지 관련하여 문의 드립니다.

### ISSUE THREAD

**Issue by jih0-kim** [DatathonInfo/MISOChallenge-3Dobject#8]
안녕하세요, 결과 요약지와 관련하여 문의 드립니다.
제가 메일을 미처 정확히 확인하지 못하고 깃허브 인포 페이지에서 날짜만 확인하여 오늘 오후 늦게까지 서버가 사용가능한 것으로 생각하였습니다.
성능 평가 결과를 확인하지 못해서 요약지에 필요한 스크린샷을 첨부드리기 어려울 것 같아 문의를 남깁니다.
그래도 그 외 다른 부분 작성하여 제출하여도 될지 알 수 있을까요?

감사합니다.

**Comment by qnqnckck** [comment]
안녕하세요 참가자님
전화 드렸던것처럼 성능평가를 제외한 요약지는 작성해서 전달 부탁드립니다.
